import { createSlice } from '@reduxjs/toolkit';

// Initial state for the counter
const initialState = {
  value: 0,
  status: 'idle', // Example of extra state property
};

// Create the counter slice
const counterSlice = createSlice({
  name: 'counter', // The name of the slice
  initialState,
  reducers: {
    increment: (state) => {
      state.value += 1; // Direct state mutation is allowed with Immer
    },
    decrement: (state) => {
      state.value -= 1;
    },
    incrementByAmount: (state, action) => {
      state.value += action.payload; // Use payload for dynamic updates
    },
    reset: (state) => {
      state.value = 0;
    },
  },
});

// Export actions generated by createSlice
export const { increment, decrement, incrementByAmount, reset } = counterSlice.actions;

// Export the reducer to be used in the store
export default counterSlice.reducer;
